### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by olavt** [matter-js/python-matter-server#657]
Seems like access to a dictionary is not properly protected against access from multiple threads.

2024-03-28 17:31:19 (MainThread) INFO [matter_server.server.device_controller] Starting Matter commissioning with code using Node ID 4 (attempt 1/3).
2024-03-28 17:31:29 (MainThread) INFO [matter_server.server.device_controller] Matter commissioning of Node ID 4 successful.
2024-03-28 17:31:29 (Dummy-2) CHIP_ERROR [chip.native.BLE] no endpoint for unsub complete
2024-03-28 17:31:29 (MainThread) INFO [matter_server.server.device_controller] Interviewing node: 4
2024-03-28 17:31:29 (Dummy-2) CHIP_ERROR [chip.native.CTL] Commissioning discovery over BLE failed: src/platform/Linux/bluez/ChipDeviceScanner.cpp:173: CHIP Error 0x00000032: Timeout
2024-03-28 17:31:29 (Dummy-2) CHIP_ERROR [chip.native.-] src/platform/Linux/bluez/ChipDeviceScanner.cpp:173: CHIP Error 0x00000032: Timeout at src/controller/SetUpCodePairer.cpp:324
2024-03-28 17:31:29 (Dummy-2) CHIP_ERROR [chip.native.BLE] BLE scan error: src/platform/Linux/bluez/ChipDeviceScanner.cpp:173: CHIP Error 0x00000032: Timeout
2024-03-28 17:31:31 (MainThread) INFO [matter_server.server.device_controller.node_4] Setting-up node...
2024-03-28 17:31:31 (MainThread) INFO [matter_server.server.device_controller.node_4] Setting up attributes and events subscription.
2024-03-28 17:31:32 (MainThread) INFO [matter_server.server.device_controller.node_4] Subscription succeeded
2024-03-28 17:31:32 (MainThread) INFO [matter_server.server.device_controller] Commissioning of Node ID 4 completed.
2024-03-28 17:31:50 (Dummy-2) CHIP_ERROR [chip.native.DIS] Timeout waiting for mDNS resolution.
2024-03-28 17:36:37 (Dummy-2) CHIP_ERROR [chip.native.DMG] Subscription Liveness timeout with SubscriptionID = 0xe0ee885f, Peer = 01:0000000000000004
2024-03-28 17:36:37 (MainThread) INFO [matter_server.server.device_controller.node_4] Previous subscription failed with Error: 50, re-subscribing in 0 ms...
2024-03-28 17:37:08 (Dummy-2) CHIP_ERROR [chip.native.DIS] Timeout waiting for mDNS resolution.
2024-03-28 17:37:32 (Dummy-2) CHIP_ERROR [chip.native.DMG] Time out! failed to receive report data from Exchange: 29086i
2024-03-28 17:37:32 (MainThread) INFO [matter_server.server.device_controller.node_4] Previous subscription failed with Error: 50, re-subscribing in 6576 ms...
2024-03-28 17:37:41 (Dummy-2) CHIP_ERROR [chip.native.EM] Failed to Send CHIP MessageCounter:255295085 on exchange 29086i sendCount: 4 max retries: 4
2024-03-28 17:37:45 (Dummy-2) CHIP_ERROR [chip.native.EM] Failed to Send CHIP MessageCounter:168333535 on exchange 29087i sendCount: 4 max retries: 4
2024-03-28 17:37:48 (Dummy-2) CHIP_ERROR [chip.native.SC] CASESession timed out while waiting for a response from the peer. Current state was 4
2024-03-28 17:37:48 (Dummy-2) CHIP_ERROR [chip.native.DMG] Failed to establish CASE for re-subscription with error 'src/protocols/secure_channel/CASESession.cpp:553: CHIP Error 0x00000032: Timeout'
2024-03-28 17:37:48 (MainThread) INFO [matter_server.server.device_controller.node_4] Previous subscription failed with Error: 50, re-subscribing in 9321 ms...
2024-03-28 17:37:48 (MainThread) INFO [matter_server.server.device_controller] Marked node 4 as unavailable
2024-03-28 17:37:57 (MainThread) ERROR [matter_server.server] Error doing task: Exception in callback MatterDeviceController._write_node_state(4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 1299, in _write_node_state
    value=dataclass_to_dict(node),
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/common/helpers/util.py", line 82, in dataclass_to_dict
    return asdict(
           ^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1284, in asdict
    return _asdict_inner(obj, dict_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1291, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in <genexpr>
    return type(obj)((_asdict_inner(k, dict_factory),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: dictionary changed size during iteration
2024-03-28 17:37:57 (MainThread) ERROR [matter_server.server] Error doing task: Exception in callback MatterDeviceController._write_node_state(4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 1299, in _write_node_state
    value=dataclass_to_dict(node),
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/common/helpers/util.py", line 82, in dataclass_to_dict
    return asdict(
           ^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1284, in asdict
    return _asdict_inner(obj, dict_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1291, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in <genexpr>
    return type(obj)((_asdict_inner(k, dict_factory),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: dictionary changed size during iteration
2024-03-28 17:37:57 (MainThread) ERROR [matter_server.server] Error doing task: Exception in callback MatterDeviceController._write_node_state(4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 1299, in _write_node_state
    value=dataclass_to_dict(node),
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/common/helpers/util.py", line 82, in dataclass_to_dict
    return asdict(
           ^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1284, in asdict
    return _asdict_inner(obj, dict_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1291, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in <genexpr>
    return type(obj)((_asdict_inner(k, dict_factory),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: dictionary changed size during iteration
2024-03-28 17:37:57 (MainThread) ERROR [matter_server.server] Error doing task: Exception in callback MatterDeviceController._write_node_state(4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 1299, in _write_node_state
    value=dataclass_to_dict(node),
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/common/helpers/util.py", line 82, in dataclass_to_dict
    return asdict(
           ^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1284, in asdict
    return _asdict_inner(obj, dict_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1291, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in <genexpr>
    return type(obj)((_asdict_inner(k, dict_factory),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: dictionary changed size during iteration
2024-03-28 17:37:57 (MainThread) ERROR [matter_server.server] Error doing task: Exception in callback MatterDeviceController._write_node_state(4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 1299, in _write_node_state
    value=dataclass_to_dict(node),
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/common/helpers/util.py", line 82, in dataclass_to_dict
    return asdict(
           ^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1284, in asdict
    return _asdict_inner(obj, dict_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1291, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in <genexpr>
    return type(obj)((_asdict_inner(k, dict_factory),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: dictionary changed size during iteration
2024-03-28 17:37:57 (MainThread) ERROR [matter_server.server] Error doing task: Exception in callback MatterDeviceController._write_node_state(4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 1299, in _write_node_state
    value=dataclass_to_dict(node),
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/common/helpers/util.py", line 82, in dataclass_to_dict
    return asdict(
           ^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1284, in asdict
    return _asdict_inner(obj, dict_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1291, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in <genexpr>
    return type(obj)((_asdict_inner(k, dict_factory),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: dictionary changed size during iteration
2024-03-28 17:37:57 (MainThread) ERROR [matter_server.server] Error doing task: Exception in callback MatterDeviceController._write_node_state(4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 1299, in _write_node_state
    value=dataclass_to_dict(node),
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/common/helpers/util.py", line 82, in dataclass_to_dict
    return asdict(
           ^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1284, in asdict
    return _asdict_inner(obj, dict_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1291, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in <genexpr>
    return type(obj)((_asdict_inner(k, dict_factory),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: dictionary changed size during iteration
2024-03-28 17:37:57 (MainThread) ERROR [matter_server.server] Error doing task: Exception in callback MatterDeviceController._write_node_state(4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 1299, in _write_node_state
    value=dataclass_to_dict(node),
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/common/helpers/util.py", line 82, in dataclass_to_dict
    return asdict(
           ^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1284, in asdict
    return _asdict_inner(obj, dict_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1291, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in <genexpr>
    return type(obj)((_asdict_inner(k, dict_factory),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: dictionary changed size during iteration
2024-03-28 17:37:57 (MainThread) ERROR [matter_server.server] Error doing task: Exception in callback MatterDeviceController._write_node_state(4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 1299, in _write_node_state
    value=dataclass_to_dict(node),
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/common/helpers/util.py", line 82, in dataclass_to_dict
    return asdict(
           ^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1284, in asdict
    return _asdict_inner(obj, dict_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1291, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in <genexpr>
    return type(obj)((_asdict_inner(k, dict_factory),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: dictionary changed size during iteration
2024-03-28 17:37:57 (MainThread) ERROR [matter_server.server] Error doing task: Exception in callback MatterDeviceController._write_node_state(4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 1299, in _write_node_state
    value=dataclass_to_dict(node),
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/common/helpers/util.py", line 82, in dataclass_to_dict
    return asdict(
           ^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1284, in asdict
    return _asdict_inner(obj, dict_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1291, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in <genexpr>
    return type(obj)((_asdict_inner(k, dict_factory),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: dictionary changed size during iteration
2024-03-28 17:37:57 (MainThread) ERROR [matter_server.server] Error doing task: Exception in callback MatterDeviceController._write_node_state(4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 1299, in _write_node_state
    value=dataclass_to_dict(node),
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/common/helpers/util.py", line 82, in dataclass_to_dict
    return asdict(
           ^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1284, in asdict
    return _asdict_inner(obj, dict_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1291, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in <genexpr>
    return type(obj)((_asdict_inner(k, dict_factory),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: dictionary changed size during iteration
2024-03-28 17:37:58 (MainThread) ERROR [matter_server.server] Error doing task: Exception in callback MatterDeviceController._write_node_state(4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 1299, in _write_node_state
    value=dataclass_to_dict(node),
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/common/helpers/util.py", line 82, in dataclass_to_dict
    return asdict(
           ^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1284, in asdict
    return _asdict_inner(obj, dict_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1291, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in <genexpr>
    return type(obj)((_asdict_inner(k, dict_factory),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: dictionary changed size during iteration
2024-03-28 17:37:58 (MainThread) ERROR [matter_server.server] Error doing task: Exception in callback MatterDeviceController._write_node_state(4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 1299, in _write_node_state
    value=dataclass_to_dict(node),
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/common/helpers/util.py", line 82, in dataclass_to_dict
    return asdict(
           ^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1284, in asdict
    return _asdict_inner(obj, dict_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1291, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in <genexpr>
    return type(obj)((_asdict_inner(k, dict_factory),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: dictionary changed size during iteration
2024-03-28 17:37:58 (MainThread) ERROR [matter_server.server] Error doing task: Exception in callback MatterDeviceController._write_node_state(4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 1299, in _write_node_state
    value=dataclass_to_dict(node),
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/common/helpers/util.py", line 82, in dataclass_to_dict
    return asdict(
           ^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1284, in asdict
    return _asdict_inner(obj, dict_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1291, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in <genexpr>
    return type(obj)((_asdict_inner(k, dict_factory),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: dictionary changed size during iteration
2024-03-28 17:37:58 (MainThread) ERROR [matter_server.server] Error doing task: Exception in callback MatterDeviceController._write_node_state(4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 1299, in _write_node_state
    value=dataclass_to_dict(node),
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/common/helpers/util.py", line 82, in dataclass_to_dict
    return asdict(
           ^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1284, in asdict
    return _asdict_inner(obj, dict_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1291, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in <genexpr>
    return type(obj)((_asdict_inner(k, dict_factory),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: dictionary changed size during iteration
2024-03-28 17:37:58 (MainThread) ERROR [matter_server.server] Error doing task: Exception in callback MatterDeviceController._write_node_state(4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 1299, in _write_node_state
    value=dataclass_to_dict(node),
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/common/helpers/util.py", line 82, in dataclass_to_dict
    return asdict(
           ^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1284, in asdict
    return _asdict_inner(obj, dict_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1291, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in <genexpr>
    return type(obj)((_asdict_inner(k, dict_factory),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: dictionary changed size during iteration
2024-03-28 17:37:58 (MainThread) ERROR [matter_server.server] Error doing task: Exception in callback MatterDeviceController._write_node_state(4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 1299, in _write_node_state
    value=dataclass_to_dict(node),
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/common/helpers/util.py", line 82, in dataclass_to_dict
    return asdict(
           ^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1284, in asdict
    return _asdict_inner(obj, dict_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1291, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in <genexpr>
    return type(obj)((_asdict_inner(k, dict_factory),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: dictionary changed size during iteration
2024-03-28 17:37:58 (MainThread) ERROR [matter_server.server] Error doing task: Exception in callback MatterDeviceController._write_node_state(4)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 1299, in _write_node_state
    value=dataclass_to_dict(node),
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/common/helpers/util.py", line 82, in dataclass_to_dict
    return asdict(
           ^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1284, in asdict
    return _asdict_inner(obj, dict_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1291, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1321, in <genexpr>
    return type(obj)((_asdict_inner(k, dict_factory),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: dictionary changed size during iteration
2024-03-28 17:38:00 (MainThread) INFO [root] Re-subscription succeeded!

**Comment by Apollon77** [comment]
Is that still a topic? We will migrate to matter,js as Basis and this issue will be not relevant there
